name: Benchmark

on:
  workflow_dispatch: {}

env:
  CI_RUST_TOOLCHAIN: 1.61.0

jobs:
  becnmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: etcd-io/etcd
          ref: v3.5.5
          path: etcd
      - uses: actions/setup-go@v3
      - run: |
          cd etcd
          go build ./tools/benchmark
          cd ../benchmark
          mv ../etcd/benchmark .
          docker pull datenlord/xline:latest
          docker pull datenlord/etcd:latest
          bash ./benchmark.sh
      - uses: actions/upload-artifact@v1
        with:
          name: benchmark-output
          path: benchmark/out
