name: Docker

on:
  pull_request:
    branches: 
      - master
    types: [closed]

jobs:
  docker:
    name: Docker
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo PR closed ...${{ github.event.pull_request.merged }}
